/*
 * torn.space
 * Copyright (C) 2026 DamienVesper
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published
 * by the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

import type { Team } from "@/common/constants";
import type { AchievementDefKey } from "@/common/defs/achievementDefs";
import type { ShipDefKey } from "@/common/defs/shipDefs";
import type { WeaponDefKey } from "@/common/defs/weaponDefs";

type TranslationMessage = "dockWorldMessage";

/**
 * Translation keys.
 * Do not edit this file unless you know what you are doing! This file updates the schema for all translation files,
 * and not updating each of the individual translation files accordingly will result in type errors!
 *
 * If you'd like to contribute to translations, contact us on Discord.
 */
export type Translation = {
    /**
     * The language code. Must be a valid {@link https://en.wikipedia.org/wiki/ISO_639-1|ISO 639-1} string.
     */
    readonly code: string;
    /**
     * Achievements that the player can obtain.
     * Shows in the base menu.
     */
    achievements: Record<AchievementDefKey, Record<"name" | "description", string>>;
    /**
     * The intro message to display when a guest team button is clicked on the main screen.
     */
    lore: Record<Team, string>;
    messages: Record<TranslationMessage, string>;
    /**
     * Ships.
     */
    ships: Record<
        ShipDefKey,
        {
            /**
             * The name for human ships.
             */
            [Team.Human]: string;
            /**
             * The name for alien ships.
             */
            [Team.Alien]: string;
            /**
             * The name for cyborg ships.
             */
            [Team.Cyborg]: string;
            /**
             * A short description of the ship to show in the shop.
             */
            description: string;
        }
    >;
    /**
     * Splash messages to show when the page is loading.
     */
    splashMessages: string[];
    /**
     * Weapons.
     */
    weapons: Record<
        WeaponDefKey | "",
        {
            /**
             * The name of the weapon.
             */
            name: string;
            /**
             * The description of the weapon.
             */
            description: string;
            /**
             * A list of kill messages to display when the weapon kills a player.
             *
             * You can use templates such as `[source]`, `[target]`, and `[weapon]`.
             *
             * If this array is not specified, the default kill message is used.
             * Do not leave an empty array!
             */
            killMessages?: string[];
        }
    >;
};
