name: Bot
on:
  push:
    branches:
      - master
    paths: &paths
      - "server/**"
      - "common/**"
      - "*.json"
      - "bun.lock"
      - ".github/workflows/bot.yml"
  pull_request:
    paths: *paths
jobs:
  bot:
    name: Bot
    runs-on: ubuntu-latest
    concurrency: ci-bot-${{ github.ref }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install Packages
        run: bun ci --filter . --filter ./common --filter ./bot

      - name: Typecheck Bot
        run: bun typecheck
        working-directory: ./bot

      - name: Build Bot
        run: bun run build
        working-directory: ./bot
